### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by YuichiTakaoka** [YuichiTakaoka/protospace-37240#1]
# URL
https://protospace-37240.herokuapp.com/

**Comment by miyu-yamamoto** [comment]
@YuichiTakaoka さん、お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ユーザーの新規登録には、プロフィールを必須としましょう。**

- [ ] **ユーザーの新規登録には、所属を必須としましょう。**

- [ ] **ユーザーの新規登録には、役職を必須としましょう。**

- [ ] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されるよう実装しましょう。**
現状、「こんにちは◯◯」と表示されておりますので、「、」と「さん」を追加しましょう

- [ ] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**
現状、プロトタイプ名をクリックしても該当するプロトタイプの詳細ページへ遷移しません

- [ ] **プロトタイプ編集ページにて、空の入力欄がある場合は、編集できずにそのページに留まるようにしましょう。**
現状、エラー画面が表示されます

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
①プロトタイプ詳細ページにて、投稿者名をクリックするとプロトタイプ一覧ページに遷移します
②プロトタイプ詳細ページにて、コメント投稿者名をクリックするとプロトタイプ一覧ページに遷移します

- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが正しく表示されるようにしましょう。**
現状、そのユーザーが投稿していないプロトタイプも表示されております

- [ ] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるようにしましょう**
現状、他のユーザーが投稿したプロトタイプの編集ページを開けてしまいます

プロトタイプにログインしようとすると、basic認証が要求される状況です。
「admin/2222」で試したところログインすることができたため、動作確認をさせていただきましたが
認証は外していただきますようお願いします。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by YuichiTakaoka** [comment]
修正しましたのでお願いいたします

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、引き続き修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移するようにしましょう**
プロトタイプ名をクリックしたときに遷移しません。

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
コメントの投稿者名をクリックしたときに正しく遷移しません。（全て、そのプロトタイプを投稿したユーザーの詳細ページへ遷移してしまいます。）

- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるようにしましょう**
そのユーザーが投稿したプロトタイプ以外も表示されています。
<img width="1134" alt="スクリーンショット_2021-12-08_12_50_36" src="https://user-images.githubusercontent.com/62644781/145145168-7e3b5c36-7a2a-49aa-b178-656a02e9c6d0.png">

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by YuichiTakaoka** [comment]
再度修正しました

**Comment by miyu-yamamoto** [comment]
@YuichiTakaoka さん、ご提出いただきありがとうございます。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
ユーザー詳細ページではなく、プロトタイプ詳細ページに遷移します
<img width="1190" alt="スクリーンショット 2021-12-08 15 24 23" src="https://user-images.githubusercontent.com/59544869/145159057-27002aa1-b307-4ca1-a1da-655f30e4652b.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by YuichiTakaoka** [comment]
再度修正しました

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、再度修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ]  **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
コメントの投稿者名をクリックしたときに正しく遷移しません。（全て、そのプロトタイプを投稿したユーザーの詳細ページへ遷移してしまいます。）

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by YuichiTakaoka** [comment]
修正しましたのでお願いします。

**Comment by miyu-yamamoto** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
